# Generated by Django 3.0.5 on 2020-04-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacechannel',
            name='channel_id',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
