# Generated by Django 3.0.5 on 2020-04-27 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0002_workspacechannel_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpaceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.WorkSpaceUser'),
        ),
    ]
