# Generated by Django 3.0.5 on 2020-04-27 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0004_auto_20200427_1047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspaceuser',
            unique_together={('username', 'user', 'workspace')},
        ),
    ]
