# Generated by Django 3.0.5 on 2020-04-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('workspaces', '0005_auto_20200427_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpaceUserConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.WorkSpace')),
            ],
            options={
                'unique_together': {('workspace', 'social_account')},
            },
        ),
    ]
