# Generated by Django 3.0.5 on 2020-04-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('workspaces', '0006_workspaceuserconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
        migrations.DeleteModel(
            name='WorkSpaceUserConnect',
        ),
    ]
