# Generated by Django 3.0.5 on 2020-04-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('workspaces', '0008_auto_20200427_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount', unique=True),
        ),
    ]
