# Generated by Django 3.0.5 on 2020-04-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_auto_20200427_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspacechannel',
            options={'verbose_name': 'Channel'},
        ),
    ]
