# Generated by Django 3.0.5 on 2020-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_auto_20200429_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceuser',
            name='user_slackid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
