# Generated by Django 3.0.5 on 2020-04-27 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(40)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(40)]),
        ),
    ]
